### ISSUE TITLE
Create docker image for this repo

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#18]
#### What data file(s) does this issue pertain to?
NA

#### What release are you using?

V2

#### Put your question or report your issue here.
Create a new docker image (once we have a new repo name 😀)

**Comment by kgaonkar6** [comment]
Is there a docker hub account we can use to push the docker image to?

**Comment by jharenza** [comment]
> Is there a docker hub account we can use to push the docker image to?

@yuankunzhu @allisonheath  i think we have an account for KFDRC, but do we have a D3b account? If not, can we create one?

**Comment by yuankunzhu** [comment]
we have 2 accounts on dockerhub
- d3bcenter: https://hub.docker.com/orgs/d3bcenter
- kfdrc: https://hub.docker.com/orgs/kfdrc

But we ended up deprecating both as they are on free tier and have pull limits per hour, which won't work for our harmonization operation. So we moved to the [Cavatica's docker registry](https://docs.cavatica.org/docs/upload-your-docker-image) instead. 

For OT, we can use cavatica, but if we don't expect high volume image pull simultaneously, we could use the dockerhub registry too or create a new one.

**Comment by jharenza** [comment]
Ok, I think we just need the free one for this - can we give @kgaonkar6 access to `d3bcenter:https://hub.docker.com/orgs/d3bcenter`?

**Comment by kgaonkar6** [comment]
Thanks both! I'm on docker hub as `gaonkark` email gaonkark@email.chop.edu

**Comment by kgaonkar6** [comment]
@yuankunzhu can I have access to push to kfdrc dockerhub account ?
if I run `docker push kfdrc/open-pedcan` I get this error:
```
 denied: requested access to the resource is denied
```

**Comment by yuankunzhu** [comment]
Created a docker repo on cavatica for this. d3b-bixu/open-pecan

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Krutika Gaonkar ***@***.***>
Sent: Friday, June 11, 2021 12:20:11 PM
To: PediatricOpenTargets/ticket-tracker ***@***.***>
Cc: Zhu, Yuankun ***@***.***>; Mention ***@***.***>
Subject: [External]Re: [PediatricOpenTargets/ticket-tracker] Create docker image for this repo (#18)


@yuankunzhu<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyuankunzhu&data=04%7C01%7CZhuY%40chop.edu%7Cec1f32497fa140b69ab908d92cf4ca25%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637590252137750727%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=7wUiCD%2BnHZzwluPSsmrIL8bswV93llpXpNDwQiyjC50%3D&reserved=0> can I have access to push to kfdrc dockerhub account ?
if I run docker push kfdrc/open-pedcan I get this error:

 denied: requested access to the resource is denied


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FPediatricOpenTargets%2Fticket-tracker%2Fissues%2F18%23issuecomment-859694156&data=04%7C01%7CZhuY%40chop.edu%7Cec1f32497fa140b69ab908d92cf4ca25%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637590252137760685%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=SU04GeSauCyCFVwF%2Fz9JnSWBaTHkxHq%2BkmV3qmR6i5k%3D&reserved=0>, or unsubscribe<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABF4MJFECJW5RI2PF4ECZJLTSIZTXANCNFSM45HEICXQ&data=04%7C01%7CZhuY%40chop.edu%7Cec1f32497fa140b69ab908d92cf4ca25%7Ca611241607b041a59bb1d146b575c975%7C1%7C0%7C637590252137770643%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=aPTDEgC5ved01xqgN6ZVbCBla%2FO3BfmMpSuhKKG6YGQ%3D&reserved=0>.

** This email originated from an EXTERNAL sender to CHOP. Proceed with caution when replying, opening attachments, or clicking links. Do not disclose your CHOP credentials, employee information, or protected health information to a potential hacker**.
