### ISSUE TITLE
Updated analysis: Independent Sample Selection

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#193]
#### What analysis module should be updated and why?

Independent sample module - to be updated so that we preferentially select WXS tumor samples when WGS and WXS are available for a particular participant.

#### What changes need to be made? Please provide enough detail for another participant to make the update.

In the step for selecting samples, instead of doing a [`distinct` call ](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/90b5e77c7f89671f3af43d80d9b13f313f6975ea/analyses/independent-samples/util/independent-samples.R#L94-L96) after randomly sample the files, we want to preferentially select WXS tumor as the biospecimen when WGS and WXS are both available.

#### What input data should be used? Which data were used in the version being updated?
v9 
histologies.tsv

#### When do you expect the revised analysis will be completed?
1-2 days

**Comment by runjin326** [comment]
@jharenza, @logstar, actually I was wrong about randomly choosing any sample - according to the [current code in here](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/0e3548fa294949734cdae9e1322722b19d02e0eb/analyses/independent-samples/01-generate-independent-specimens.R#L99-L123), we actually preferentially select WGS tumor over WXS and panel. And the `distinct` call is actually after these selections - we randomly choose 1 WGS and then we randomly choose 1 WXS or panel. We then `bind_rows` to generate the final file. 
Sorry about the confusion! 
We can now update to prioritize WXS and the randomly choose 1 WGS or panel instead correct? Do we still want to write out WXS-only list as we do now for WGS samples?

**Comment by jharenza** [comment]
hmm, let me think on this - we would not want panel over WGS for sure, as it is a smaller gene panel. I think the reason for selecting WGS over WXS may have been for CNV calls, esp since we have better coverage for breakpoints in WGS. But we probably also ought to have a module exploring consistency of SNV and CNV calls across WXS/WGS...I almost wonder if we should preferentially choose WXS over WGS for SNV (should detect more/better) and CNV WGS over WXS for CNV since we have a good consensus method and can also use this for chromothripsis (cannot use WXS very well). cc @afarrel for thoughts

**Comment by afarrel** [comment]
I actually had this conversation with Asif earlier.  My thoughts are that it should be pipeline/module dependent. So I agree for CNV WGS shouled be preferred. For SNV, WXS should be preferred since it has deeper coverage. Furthermore, since this platform is centered around the PMTL (and novel genes), the mutations in the coding (exonic) regions of genes are what might be most important to the end-users. I guess for chromothripsis, WGS should probably be preferred.

**Comment by jharenza** [comment]
Sounds good and we agree- thanks! @runjin326 will you outline tickets as we describe above? So we will have to create additional independent lists which prefer wxs (can keep the wgs preferred ones now), and then use certain lists by module as outlined above.

**Comment by runjin326** [comment]
@jharenza, @afarrel thanks for clarifying! For some reason I missed Jo Lynne's comment but I would generate independent sample lists with *_wxs_prefer* suffix and specify in the README that these lists will be used for SNV only.
