### ISSUE TITLE
Primary site for some samples are weird 

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#257]
#### What data file(s) does this issue pertain to?
histologies.tsv

#### What release are you using?

v9/v10 - the issue is already present in v9. Did not check v8 though. 

#### Put your question or report your issue here.
Some entries in `histologies.tsv` file have `primary_site` that are lumping together or truncated. 
Need to revisit how we get those information and format them correctly if possible. 
Attaching a file with primary sites with issue after manually look through all primary sites:
[primary_site_weird.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/7596852/primary_site_weird.txt)

Additionally, here is a breakdown of those samples: 
```
> weird_primary %>% select(cohort, cancer_group) %>% table()
        cancer_group
cohort   Neuroblastoma
  GMKF             155
  TARGET           325
```
Probably should revisit the primary site calling for all GMKF and TARGET NBL to make sure everything is fixed.

**Comment by ewafula** [comment]
> #### What data file(s) does this issue pertain to?
> histologies.tsv
> 
> #### What release are you using?
> v9/v10 - the issue is already present in v9. Did not check v8 though.
> 
> #### Put your question or report your issue here.
> Some entries in `histologies.tsv` file have `primary_site` that are lumping together or truncated. Need to revisit how we get those information and format them correctly if possible. Attaching a file with primary sites with issue after manually look through all primary sites: [primary_site_weird.txt](https://github.com/PediatricOpenTargets/ticket-tracker/files/7596852/primary_site_weird.txt)
> 
> Additionally, here is a breakdown of those samples:
> 
> ```
> > weird_primary %>% select(cohort, cancer_group) %>% table()
>         cancer_group
> cohort   Neuroblastoma
>   GMKF             155
>   TARGET           325
> ```
> 
> Probably should revisit the primary site calling for all GMKF and TARGET NBL to make sure everything is fixed.

@runjin326,  this how it is reported in the Neuroblastoma metadata files both GMFK and TARGET.  Look and the `IDCO Description` column in the the example file attached. Each cell of the excel column has multiple lines (what ends up looking like lumping together in tsv histologies file), Looks pretty,  but not so when read in with either R or python and write to tsv output file.  In my histologies code, I performed a second step using regex to make sure each cell entry is not written out to multiple lines, hence the lumping together that you see. But those are legit entries for a sample_id record. Unfortunately,  some seem to be truncated. Because cell entries are different, it is very challenging to come up with regex code that would format each of the thousand of sample_id cells independently. 

You can read in the attached example excel file and write out to a TSV output file.  All the multi-line `IDCO Description` column  entries except the first are each on new line first column.  That is where the regex reformatting comes in to lump them together (each primary site term separated with whitespace) on the same line with respective sample_id record. 
```
library(readxl)
df <- read_xlsx("~/Downloads/TARGET_NBL_ClinicalData_Validation_20200507.xlsx")
write_tsv(df, "~/Downloads/TARGET_NBL_ClinicalData_Validation_20200507.tsv")
```
[TARGET_NBL_ClinicalData_Validation_20200507.xlsx](https://github.com/PediatricOpenTargets/ticket-tracker/files/7597499/TARGET_NBL_ClinicalData_Validation_20200507.xlsx)
`

**Comment by runjin326** [comment]
@ewafula, thanks for sending along the excel file - looks like the excel file has all the correct information and they are just formatting issues so should not be hard to fix. I will look into that and let you know.

**Comment by runjin326** [comment]
@ewafula, I have now fixed the primary site of the excel file - attached here: 
[TARGET_NBL_ClinicalData_Validation_20200507.xlsx](https://github.com/PediatricOpenTargets/ticket-tracker/files/7626166/TARGET_NBL_ClinicalData_Validation_20200507.xlsx)
Could you please use it to update the current histologies file we have? Thanks!

**Comment by ewafula** [comment]
> @ewafula, I have now fixed the primary site of the excel file - attached here: [TARGET_NBL_ClinicalData_Validation_20200507.xlsx](https://github.com/PediatricOpenTargets/ticket-tracker/files/7626166/TARGET_NBL_ClinicalData_Validation_20200507.xlsx) Could you please use it to update the current histologies file we have? Thanks!

@runjin326, thanks, but there are several of the clinical files for NBL samples with different formats from different sources, some Maris Lab, Diskin Lab, TARGET portal (multiple), and GDC portal. Remember we have been progressively amending and adding samples to the histologies file since the beginning of the project. Therefore, the feasible approach for v11 is for me to manually work through all the OT NBL clinical source files and create a clean samples_id-primary_site mapping file for updating in v11.

**Comment by runjin326** [comment]
@ewafula, thanks Eric - I think you can use the one I attache for TARGET and for Maris and others, yes could you please manually work through all the clinical sources and generate a mapping file? 
Also, please make sure when you manually fix them, the truncated issue that we saw here is being fixed as well. Thanks!

**Comment by ewafula** [comment]
> df <- read_xlsx

**Comment by ewafula** [comment]
> @ewafula, thanks Eric - I think you can use the one I attache for TARGET and for Maris and others, yes could you please manually work through all the clinical sources and generate a mapping file? Also, please make sure when you manually fix them, the truncated issue that we saw here is being fixed as well. Thanks!

@runjin326, about the truncated primary_site ICDO Descriptions, they not formatting issues. They are all truncated in the GMKF Maris Lab clinical source file, [2019-09-30-gmkf_clinical_elements.csv](https://github.com/ewafula/D3b-codes/blob/OpenPedCan_histologies/OpenPedCan_histologies/input/KFNBL/2019-09-30-gmkf_clinical_elements.csv). May be replacing them with similar ICDO Descriptions from TARGET if the USI ID is the same? 

Example: `Retroperitoneum Periadrenal tissue Perinephric tissue Per` in Maris Lab file  and `Retroperitoneum  Periadrenal tissue;  Perinephric tissue;  Peripancreatic tissue;  Perirenal tissue;  Retrocecal tissue;  Retroperitoneal tissue` in TARGET file

**Comment by runjin326** [comment]
@ewafula, yes that would work - I actually saw that one of the entries in TARGET also has an additional `Per` but I used the ICDO field (it contains a code) to match and that should be good. Using the USI ID to replace them is a good idea!

**Comment by jharenza** [comment]
Just pointing out that USI is a patient identifier, so you'll have to get the specimen identifiers to match for this.

**Comment by ewafula** [comment]
> Just pointing out that USI is a patient identifier, so you'll have to get the specimen identifiers to match for this. However, the better solution would probably be to get an updated source from COG. Cc @afarrel

Sure, @jharenza. I will discuss with @afarrel before updating. Maybe he as the original file some where ICDO Descriptions field entries are not truncated as currently present in CSV file that I used for the create the OT histologies file.

**Comment by jharenza** [comment]
@afarrel or @chinwallaa can you ask John if we can get an update on the [2019-09-30-gmkf_clinical_elements.csv](https://github.com/ewafula/D3b-codes/blob/OpenPedCan_histologies/OpenPedCan_histologies/input/KFNBL/2019-09-30-gmkf_clinical_elements.csv) file to include non-truncated primary sites, along with updated survival information since this is going on 3 years old.

**Comment by jharenza** [comment]
this is not urgent for v11, so removing that label

**Comment by afarrel** [comment]
[GWAS_TARGET_listing_20220331_FZ.xlsx](https://github.com/PediatricOpenTargets/ticket-tracker/files/8611680/GWAS_TARGET_listing_20220331_FZ.xlsx)
All the patients in the that gmkf list are in this list.

**Comment by jharenza** [comment]
Closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/188
