### ISSUE TITLE
Proposed Analysis: Identification of stably expressed housekeeping genes for batch correction

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#27]
#### What are the scientific goals of the analysis?
To determine stably expressed housekeeping genes between cancer + GTEX samples.

#### What methods do you plan to use to accomplish the scientific goals?
Adapted from [this comment](https://github.com/PediatricOpenTargets/ticket-tracker/issues/10#issuecomment-845131523),
1. Run a first-pass DGE analysis using TMM normalization between cancer (TARGET NBL, GMKF NBL, PBTA) and normal (all GTEX) using the full housekeeping gene list, below.
[Housekeeping_GenesHuman.csv](https://github.com/PediatricOpenTargets/ticket-tracker/files/6548764/Housekeeping_GenesHuman.csv)
2. Identify and create a table of non-significantly altered genes as the negative control gene set for downstream batch correction.

#### What input data are required for this analysis?
counts data for TARGET NBL, GMKF NBL, GTEX NBL (we only have counts for GMKF NBL currently in this release and counts for PBTA in the OpenPBTA-analysis repo, so we will need to gather these files, which I think @komalsrathi can help with when she is back next week).

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
0.5 day

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@logstar 

#### What relevant scientific literature relates to this analysis?

cc @aadamk for 1, as we will be constantly adding more histologies, do you think we should do this as separate DE analyses or lump all cancers together for this first analysis? Initially, we wanted to test TARGET NBL and GMKF NBL since we know what the output would look like, so we can start there, but assuming this will change as we add more histologies.

**Comment by aadamk** [comment]
@jharenza - unless a pan-cancer vs normal analysis will be part of the OT deliverables, I would be inclined to keep this histology-specific. This is because the estimation of the magnitude of the batch effect depends on the input data. A pan-cancer vs normal first-pass comparison will likely not give the same repertoire of negative control genes as compared to an NBL vs normal comparison. Any downstream histology-specific analyses (e.g. DGE or clustering) would likely be erroneously influenced by an estimation of batch effect derived from a pan-cancer first-pass DGE analysis.

**Comment by jharenza** [comment]
Sounds good- let's focus on NBL vs GTEX first!

**Comment by aadamk** [comment]
Closing to clean up batch correction tickets - feel free to re-open if still needed.
