### ISSUE TITLE
Update download data script

### ISSUE THREAD

**Issue by runjin326** [PediatricOpenTargets/ticket-tracker#270]
#### What data file(s) does this issue pertain to?
`gencode.v27.primary_assembly.annotation.gtf.gz`
`GRCh38.primary_assembly.genome.fa.gz`

#### What release are you using?

v10

#### Put your question or report your issue here.
Since now we would be using GENCODE v38 to match molecular target platform, we should use release 38 in our data download.

Please update the download data script (https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/download-data.sh) to download release 38 instead of 27 - specified in [these lines](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/0bf263c5c784c6596836fef396d1d8735b9260c8/download-data.sh#L49-L70).

**Comment by jharenza** [comment]
@runjin326 when this becomes a PR, will you make this v11 (or maybe we can start using some nomenclature like 10a, 10b, 10c for updates which aren't major - although we ought to create rules around those if we do. I suggested letters because the releases create folders so not to have periods in folders).

**Comment by runjin326** [comment]
@jharenza - sure! Actually I think I would just update this when we release v11 and test with downloads of all other data files to avoid confusion.

**Comment by jharenza** [comment]
Closed with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/188
