### ISSUE TITLE
Investigate analysis: SNV frequencies

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#284]
#### What analysis module should be updated and why?
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/snv-frequencies

#### What changes need to be made? Please provide enough detail for another participant to make the update.
The frequencies on the MTP are not aligning with those on pedcbio. Pedcbio is running v7 here, but in checking some PBTA samples which should theoretically have not changed between v7 and v10, there are discrepancies. Can we investigate this code?

Two examples are the following:
1. [CTNNB1 in craniopharyngioma](https://ppdc-otp-qa.bento-tools.org/evidence/ENSG00000168036/EFO_1000209). On MTP, the frequency in overall dataset is 67.57% (25/37), but in [pedcbio](https://pedcbioportal.kidsfirstdrc.org/results/oncoprint?cancer_study_list=ped_opentargets_2021&case_set_id=ped_opentargets_2021_pbta_craniopharyngioma&Action=Submit&gene_list=CTNNB1) is 19% (3/16).
2. [CTNNB1 in medulloblastoma](https://ppdc-otp-qa.bento-tools.org/evidence/ENSG00000168036/EFO_0002939). On MTP, the frequency in overall dataset is 12.37% (12/97), but in [pedcbio](https://pedcbioportal.kidsfirstdrc.org/results/oncoprint?cancer_study_list=ped_opentargets_2021&case_set_id=ped_opentargets_2021_pbta_medulloblastoma&Action=Submit&gene_list=CTNNB1) is 11% (13/118).

There is a separate issue in that pedcbio is now counting fusions (SVs) as a part of the oncoprint (@migbro, not sure in which version this was added), so the 13/118 would actually be 12/118 in our SNV table. We should have a discussion as to how we want to handle this - I don't think we will want to combine the data, but we also will have to be aware this won't align with pedcbio, especially in cancers in which we observe both SNVs and fusions within a single gene (eg - BRAF in LGG): [MTP - 14.02%, 30/214](https://ppdc-otp-qa.bento-tools.org/evidence/ENSG00000157764/MONDO_0016685)https://ppdc-otp-qa.bento-tools.org/evidence/ENSG00000157764/MONDO_0016685 vs [pedcbio - 60%, 167/285](https://pedcbioportal.kidsfirstdrc.org/results/oncoprint?cancer_study_list=ped_opentargets_2021&case_set_id=ped_opentargets_2021_pbta_low-grade_glioma_astrocytoma&Action=Submit&gene_list=BRAF). An alternative is to go back and add the fusions the "old way", but that does not conform to the software standards anymore.

#### What input data should be used? Which data were used in the version being updated?
v7/10

#### When do you expect the revised analysis will be completed?
1 week

#### Who will complete the updated analysis?
@logstar - since you have the most knowledge about this analysis, and have used the pedcbio api, can you do some quick checks here?

cc @afarrel

**Comment by logstar** [comment]
@jharenza Thank you for checking the data and describing the discrepancies.

I will start with checking the total number of [craniopharyngioma](https://ppdc-otp-qa.bento-tools.org/evidence/ENSG00000168036/EFO_1000209) and [medulloblastoma](https://ppdc-otp-qa.bento-tools.org/evidence/ENSG00000168036/EFO_0002939) patients in v7 and v10 data, using histology.tsv, snv-consensus-plus-hotspots.maf.tsv.gz, and independent sample lists.

**Comment by logstar** [comment]
@jharenza Following are the main causes of the MTP-vs-pedcbio discrepancies of craniopharyngioma and medulloblastoma:

- The additional craniopharyngioma patients in v10 MTP are categorized as "Adamantinomatous Craniopharyngioma" in v7 pedcbio.
- The additional medulloblastoma patients in v7 pedcbio only have RNA-seq specimens. The `snv-frequencies` module only include patients in `wgswxspanel` independent sample lists, so MTP SNV results do not include patients that only have RNA-seq samples.

There is a minor issue in `snv-frequencies` module. The `snv-frequencies` module results currently do not include `wgswxspanel` tumor biospecimens that only have synonymous variants, because only non-synonymous variant rows are kept in MAF file before intersecting `Kids_First_Biospecimen_ID` between MAF file and histology file. Assuming nearly all tumor biospecimens have at least one non-synonymous variant, only a few biospecimens should be left out by this issue.

I will create a new ticket for the `snv-frequencies` issue and fix it in a PR.
