### ISSUE TITLE
Add gtex to cancer group

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#294]
Add gtex to cancer group and cancer group detailed to enable pedcbio visualization (per @adamcresnick)

@jharenza will update the file for @migbro

**Comment by logstar** [comment]
@jharenza - `cancer_group` may have been used in certain analysis modules and API to generate results for MTP, with the assumption that gtex samples have `NA` in `cancer_group`.

I was wondering if a new column named `pedcbio_cancer_gtex_group` could be created for pedcbio visualization. The `pedcbio_cancer_gtex_group` column could have detailed cancer groups.

cc @migbro

**Comment by migbro** [comment]
Um, sure, I think adding another column to the histologies file is fine, unless you wanna go a slightly different direction, like subset the histologies and create and cBio-specific columns in that one. I mention that because Run has a cBio naming module that also gets run on the histologies file in order to make the sample naming compatible with the platform. Either way, just commit to one of those tactics and let me know where to pick it up

**Comment by jharenza** [comment]
@logstar this won't affect the main histologies file - I think we have a module for a pedcbio specific file and if not, we will make one!

**Comment by logstar** [comment]
> @logstar this won't affect the main histologies file - I think we have a module for a pedcbio specific file and if not, we will make one!

@jharenza - Thank you for letting me know. Sorry that I was assuming that this issue would change the`cancer_group` column in main histologies file.

Please disregard my comment and suggestion.

cc @migbro

**Comment by migbro** [comment]
So...are you asking me to patch current histologies file I am working off of @jharenza ?

**Comment by jharenza** [comment]
no worries @logstar - I wasn't totally clear!

**Comment by jharenza** [comment]
Updated pedcbio file in https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/170

**Comment by jharenza** [comment]
updated in pedcbio
