### ISSUE TITLE
Some methylation IDs missing clinical information

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#350]
#### What data file(s) does this issue pertain to?
histologies-base-adapt.tsv, but presumably this is coming from KF 

#### What release are you using?

current 2022-07-08

#### Put your question or report your issue here.

The samples below are missing: `sample_type`, `tumor_descriptor`, `primary_site`, `pathology_diagnosis`, `pathology_free_text_diagnosis` (if any), `extent_of_tumor_resection` (if avail), but these fields are available in CBTN-ALL on RStudio Connect and some of the info seems to be in KidsFirst, but not sure if it is complete, since not visible.

```
Kids_First_Biospecimen_ID sample_id  sample_type  age_at_diagnosis_days
BS_BETQ48X0	7316-5747	Not Reported    Not Reported		
BS_CK0BY1MB	7316-5757	Not Reported   1260		
BS_SZ9SVSBH	7316-4274	Not Reported   4330
```

There is also a disconnect between `age_at_diagnosis_days` in the warehouse histologies file (above) vs CBTN-All in RStudio, below:
```
Kids_First_Biospecimen_ID sample_id   age_at_diagnosis_days
BS_BETQ48X0	7316-5747   3525		
BS_CK0BY1MB	7316-5757   1950		
BS_SZ9SVSBH	7316-4274   5697
```

@nicholasvk I can manually assign all of this information for this iteration, but can you take a look at these when you have a chance?

**Comment by nicholasvk** [comment]
This appears to be a data entry issue on the Nautilus side. Based on the definition for source_text_tissue_type that was provided by Adam R. we evaluate attributes of the parent aliquot in Nautilus, specifically the parent sample type and sample category. The category is not populated for these records in Nautilus. The reason other diagnosis attributes are not populated is because we use the source_text_tissue_type as a filter because we have different logic for Normal vs. Tumor in terms of how we want to populate the diagnosis fields. Since these records do not have source_text_tissue_type set to Tumor they are not in our intermediate pbta diagnosis table so when we join to the samples the values are null and are then labeled "Not Reported". 

Long explanation, but wanted to capture the background. I think the quick fix here would be to see if the BRU team can fill in the needed data so values populate as expected. Long term, I think we need to revisit the definition for how we are defining source_text_tissue_type because this has come up in the past. If everyone agrees on what fields to evaluate we can look at adding in validation rules in the warehouse to catch when these are not populated so that we aren't catching them downstream. We can also revisit the pbta diagnosis filter logic to evaluate if that still makes sense or not.
