### ISSUE TITLE
`7316-356` has multiple extent of tumor resection 

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#366]
#### What data file(s) does this issue pertain to?
histologies.tsv

#### What release are you using?

v11 OPC, v22 OpenPBTA

#### Put your question or report your issue here.
7316-356 went from having `Partial resection` in v21 OpenPBTA to `Partial resection;Gross/Near total resection` in v22. It looks like this is stemming from a concatenation of Diagnosis + 3 month update records, the latter of which @youngnm tells me should be removed from the data warehouse and CBTN all.

cc @youngnm @nicholasvk

**Comment by jharenza** [comment]
This was manually updated in the V11 `histologies-base.tsv` file with https://github.com/PediatricOpenTargets/OpenPedCan-analysis/pull/188, but can we confirm this was updated in the data warehouse/CBTN all shiny app @youngnm @nicholasvk ?

**Comment by jharenza** [comment]
@youngnm can you check this one as well?

**Comment by youngnm** [comment]
In the short term, is it possible for you to filter out the 3 month update records on your end? I'll raise this as a discussion item with the larger team because it's a major change to CBTN-All. Not sure what the timeline looks like yet.

**Comment by jharenza** [comment]
I realized I never responded @youngnm - I have already taken care of this manually!

**Comment by nicholasvk** [comment]
I don't think the answer here is to "remove" these from the data warehouse. My understanding is that we will no longer be collecting 3 month updates prospectively, but the existing records captured before that decision are valid. I think we should confirm these values with the CRC team and then make a decision on how to proceed. If both entries are valid we can:
1. Keep concatenated as is.
2. Develop a coding rule to prioritize one over the other (i.e. - use the 3 month update value because its the latest or some other rule)

**Comment by jharenza** [comment]
>Develop a coding rule to prioritize one over the other (i.e. - use the 3 month update value because its the latest or some other rule)

Some of these are tricky and have to be done on a sample to sample basis. I had confirmed all of these with Jenn before any updates and for this sample, the coding logic here should be: For `7316-356` --> `Partial resection`. We do not want to use a 3 month update for tumor resection because the genomic data is for the initial visit, and at that visit, there was only partial resection. Can we add this upstream on your end if we are going to maintain 3 month updates?
