### ISSUE TITLE
Updated analysis: independent sample list

### ISSUE THREAD

**Issue by kgaonkar6** [PediatricOpenTargets/ticket-tracker#37]
#### What analysis module should be updated and why?
independent-samples

#### What changes need to be made? Please provide enough detail for another participant to make the update.
Currently the module creates a sample list of  : 
PBTA primary specimens  ( only with WGS OR WGS + WXS )
PBTA primary and secondary specimens  ( only with WGS OR WGS + WXS )

We have an updated histology file with KF+TARGET+TCGA+PBTA data which needs to run through the module. 
Additionally also want separate files for secondary specimens only 

#### What input data should be used? Which data were used in the version being updated?
histologies.tsv

#### When do you expect the revised analysis will be completed?
1-2 days

#### Who will complete the updated analysis?
@kgaonkar6

**Comment by runjin326** [comment]
`tumor_types` column no longer exist  - use `tumor_descriptor` to separate primary from secondary and from others? Which descriptor belong to first or second or other? 
<img width="775" alt="image" src="https://user-images.githubusercontent.com/47674661/122681913-9b0c4580-d1c4-11eb-9c81-2dd18d94496b.png">

Final outputs will then be: 
`independent-specimens.wgs.primary.tsv`, `independent-specimens.wgs.secondary.tsv`, i`ndependent-specimens.wgs.primary-plus.tsv`, `independent-specimens.wgswxs.primary.tsv`, `independent-specimens.wgswxs.secondary.tsv`, i`ndependent-specimens.wgswxs.primary-plus.tsv`?

**Comment by jharenza** [comment]
hey @runjin326! `tumor_types` is actually a function here:

https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/5809781824c4804a2da2a01862af5b87af277cf0/analyses/independent-samples/independent-samples.R#L21-L64

What you would change would be some information within the function, here:
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/5809781824c4804a2da2a01862af5b87af277cf0/analyses/independent-samples/independent-samples.R#L27

For this, you would change it to:
```
primary_descs <- c("Initial CNS Tumor", "Diagnosis", "Primary tumor)
```

For final outputs, I think we would also want to append `panel` to the filenames which include `*wgs.wxs*`, for ex: `independent-specimens.wgswxspanel.primary.tsv` since we will have 499 NBL panel samples.

**Comment by runjin326** [comment]
Thanks @jharenza for the clarification!

**Comment by runjin326** [comment]
@kgaonkar6, what do you mean by "Additionally also want separate files for secondary specimens only"?

**Comment by kgaonkar6** [comment]
In the current code we generate the following output:
`independent-specimens.<experimenatal_strategy>.<tumor_type>.tsv` 

1. The experimenatal_strategy are coded as `wgs` for only WGS sample list ,`wgswxs` for WGS+WXS sample list and `rnaseq` for RNA-Seq sample list. 

3. The`tumor_type` are as follows:
- "primary" samples that have tumor_descriptor as follows:
`primary_descs <- c("Initial CNS Tumor", "Diagnosis", "Primary tumor)`
-  "primary-plus" which is termed as "prefer_primary" in code is a sample list where samples with primary tumor_descriptors are preferred but fall back to other non-primary types when primary does not exist

In addition to the above we want to add the following independent <tumor_type> as well:
- "secondary" samples would be any sample which doesn't have the above`primary_descs`  in tumor_descriptor column
