### ISSUE TITLE
Bix Dev PedcbioPortal Support: Create project for v11 OpenPedCan

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#374]
# 🆘

#### [Required] How would you most generally describe your issue? 
- [x] Update data for project in pedcbio portal
- [x] Create new project called `openpedcan` and start versioning
- [ ] Questions related to data on pedcbio portal 

#### If an update to a project, provide links to the input files that should be used and descriptions we might find helpful. If new `case_set_ids` need to be added, please provide instructions below.

Release V11
https://s3.amazonaws.com/d3b-openaccess-us-east-1-prd-pbta/open-targets/v11

@migbro we can discuss the new case set ids, based on how you have handled DGD in the past

#### Provide the manifest (or a link to a manifest) that will be used to select samples
`histologies.tsv`

**Comment by jharenza** [comment]
Hi @migbro 

>case_set_ids

I think we will need some new, based on cohort "CHOP DGD" being added here, and since we added additional PBTA samples, those will change, but the rules should be the same, so I imagine you can just rerun previous code to get these

For project name, how about we iterate as:
`openpedcan_v11` and so forth?

**Comment by migbro** [comment]
Link above doesn't work, but did find it, here is the s3 uri:
s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/v11/

I assume I should use the following:
CNV: `consensus_wgs_plus_cnvkit_wxs.tsv.gz`
SNV: `snv-consensus-plus-hotspots.maf.tsv.gz`
RNA expression: `gene-expression-rsem-tpm-collapsed.rds`
RNA fusion: `fusion-putative-oncogenic.tsv`

As for CHOP_DGD...is that like the same samples Mark Welsh processed a while back?

**Comment by jharenza** [comment]
Yes, for above, but also more:

DGD:
`snv-dgd.maf.tsv.gz`
``fusion-dgd.tsv.gz
 Note: the TSBs here are bs_ids and not the old DGD sample ids. Yes to same samples Mark processed.

TCGA:
`tcga-gene-expression-rsem-tpm-collapsed.rds`


I think that's it, unless you can handle methylation arrays 😆

**Comment by jharenza** [comment]
I wonder if we need to treat TCGA as a separate case_id as we did GTEX, but instead of normal samples, we make it "Adult tumors" or something, so they aren't lumping together..?

**Comment by migbro** [comment]
So, funny thing about that, it might be possible I can handle methylation arrays: https://docs.cbioportal.org/file-formats/#methylation-data
If you have a deadline though, I think it's best to load the usual, then revisit and update. Otherwise, I'd need to like, pull someone off something else...which I am tempted to do to clean this up a bit.

**Comment by jharenza** [comment]
Oh cool - yeah, how about the normal load first, then methylation later!

**Comment by migbro** [comment]
Ok, an update on attempting to convert v11 histologies to cBio format
1. Initially, I had about 3000 warnings about invalid names. The first culprit I found was because Methylation has since been added, and we will do that next time
2. Removing Methylation cut the errors down to ~800. After some digging, I think with the addition of DGD, my code is looking at teh experiment type and doing an error check if a cBio ID has two of the same assay type. Said another way, each cBio ID can have at most one _each_ of an experiment type assigned. If 2 DNA or two RNA were assigned, it throws a warning. Having said all that, histologies file makes no distinction between fusion and panel sequencing, they are both labeled as `Targeted Sequencing`, causing the error.

Thoughts on handling #2? In this case, is DNA being used for DGD in both the fusions and snv calls, so technically `Targeted Sequencing` for both is correct? If so...I'll have to think about how to handle/adjust.

**Comment by jharenza** [comment]
Hi yes, to distinguish DNA and RNA, RNA has a value in RNA_library.

**Comment by migbro** [comment]
Thanks! Ok, after adding some code to catch this, modified Run's code to let TCGA through and fixed a different issue related to DGD as well as added a blacklist function to handle all the samples with poly A and stranded RNA libraries, the data clinical sheets look promising. I will move on with the rest of the steps and see how validation goes. With any luck, I can use this to write a wrapper script in the end...maybe.

**Comment by migbro** [comment]
So, the latest snag is with RNAseq data. The TCGA dataset was done with GENCODE 36 I believe, and GENCODE 39 is still in the works for us. The TCGA set has ~20k more entries. I could merge only on th ecommon ones and the breakdown looks like:
```R
> nrow(merged_rsem)
[1] 33058
> nrow(tcga_rsem)
[1] 59427
> nrow(main_rsem)
[1] 34245
```
Or perhaps, do some kind of outer join to keep all the existing entries from GENCODE 27. Those are my leading solutions

**Comment by migbro** [comment]
So, so close.
I have merged the RNA on common hugo symbols, updated the code to handle DGD (fusions had entrez col removed on merge for some reason?! It ends up being unused, but should still be there with blank entries). Final validation fails because the DGD mafs had the empty values for `t_ref_count	t_alt_count	n_depth	n_ref_count	n_alt_count` replaced with `NA` instead of left blank. In the maf files, I think in general, if a field is blank that should be numeric, just leave it blank. @jharenza can this be fixed by someone, or do I need to hack this?

**Comment by jharenza** [comment]
Ahh @HuangXiaoyan0106 prepared the DGD files so we can have her update for you (but not replace in v11- can we put these in a v12 folder so they are updated for then?)

**Comment by jharenza** [comment]
actually, I will update this for you now, and add here: s3://d3b-openaccess-us-east-1-prd-pbta/open-targets/v12/ so @HuangXiaoyan0106 no worries!

**Comment by jharenza** [comment]
@migbro I added the files to the v12 folder.

**Comment by chinwallaa** [comment]
@migbro @logstar not sure if this is related, but do we know what the concordance of gene symbols in OpenPedCan/PMTL/MTP is with whats used in CBioPortal.  @logstar had identified that some of the URL links from MTP to CbioPortal had different (updated) genesymbols

**Comment by migbro** [comment]
@jharenza , the maf update seems to have worked thanks. The fusion update is positionally sensitive (Mark had basically made the DGD fusion output cBio-ready). I had already hacked my way around it, but Entrez ID should be second column. @chinwallaa no, not really related as I load what I get from MTP as-is into the portal. It may have some differences/equivalencies that it internally interprets, but I don't know what exactly they are

**Comment by jharenza** [comment]
Oh jeez, ok. I can update that later. I had to look at the docs for column name bc our putative oncogenic file doesn't have that either - assume you add that column?

**Comment by migbro** [comment]
Correct, I do add that column as part of the ETL normally

**Comment by migbro** [comment]
Ok @jharenza @chinwallaa @logstar , I have loaded v11 into the **QA** server here: https://kf-strides-cbioportal-qa.kidsfirstdrc.org/study/summary?id=openpedcan_v11
If this looks good, I can push to prod and close this out.

**Comment by jharenza** [comment]
@migbro this looks good. I think the only update we will need is updating TCGA case set IDs to not be counted in the "All cohorts" cancer groups. For example, TCGA LGG are now mixed with PBTA, LGG, etc in the "LGG" group. We will want this to be pediatric only.

**Comment by chinwallaa** [comment]
@jharenza do we also need to exclude DGD panel case set IDs here (or not related) - as to not include in the "All cohorts" cancer group to coordinate with the MTP v1.1 summary tables  - specifically for snv & fusion frequencies analytics ?

**Comment by jharenza** [comment]
@migbro @chinwallaa disregard above as we can handle this on the api end

**Comment by migbro** [comment]
Load looks successful: https://pedcbioportal.kidsfirstdrc.org/study/summary?id=openpedcan_v11
If there is an issue, we can reopen or create a new ticket to address.
