### ISSUE TITLE
Bix Dev PedcbioPortal Support: Update OpenPBTA study with v22 data

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#376]
# 🆘

#### [Required] How would you most generally describe your issue? 
- [x] Update data for project in pedcbio portal - https://pedcbioportal.kidsfirstdrc.org/study/summary?id=openpbta
- [ ] Questions related to data on pedcbio portal 

#### If an update to a project, provide links to the input files that should be used and descriptions we might find helpful. If new `case_set_ids` need to be added, please provide instructions below.

https://s3.amazonaws.com/d3b-openaccess-us-east-1-prd-pbta/data/release-v22-20220505

#### Provide the manifest (or a link to a manifest) that will be used to select samples
`pbta-histologies.tsv`

**Comment by migbro** [comment]
Assigning to @sakshamphul .
1. From the bucket above (since it's open access, just add the flag `--no-sign-request` to your aws command, like: `aws s3 ls --no-sign-request d3b-openaccess-us-east-1-prd-pbta/data/release-v22-20220505/`), grab the `pbta-histologies.tsv` file
2. On the cBio ec2 instance I have, in `/home/ubuntu/mount/openpbta/study_build`, rename the `data_clinical*` files, adding `.old` just for safe keeping.
3. Run `COLLABORATIONS/openPBTA/clinical_to_datasheets.py` from the cBioportal ETL repo, with the following inputs:
`-f COLLABORATIONS/openPBTA/header_desc.tsv -c `_pbta_file_you_downloaded_`-p `/home/ubuntu/mount/pbta_all/datasheets/data_clinical_sample.txt`. That last argument is using the sample sheet from the pbta_all study to ensure cBio sample naming is consistent across the two studies.
4. You should now have updated versions of the data_clinical* files. If you get errors, I can help. If not, follow up with me for upload and jenkins job steps

**Comment by jharenza** [comment]
Hi @sakshamphul - checking in on the status of this ticket please.

**Comment by migbro** [comment]
Ok, after reviewing errors Saksham got when running the clinical part, and patching the code to accomodate the loss of the parent aliquot id column, I think it might be best to pull from the latest release and re-run. Files can be gotten from aws and from here:
https://cavatica.sbgenomics.com/u/cavatica/openpbta/files/#q?path=release-v22-20220505

Files to be downloaded are:
```
consensus_seg_annotated_cn.tsv.gz
pbta-cnv-consensus.seg.gz
pbta-fusion-putative-oncogenic.tsv
pbta-gene-expression-rsem-tpm-collapsed.rds
pbta-snv-consensus-plus-hotspots.maf.tsv.gz
```
I'd suggest renaming the `/home/ubuntu/mount/openpbta/study_build` dir to `/home/ubuntu/mount/openpbta/study_build.old`, create a fresh `/home/ubuntu/mount/openpbta/study_build/` dir, move the new histology file there and and put the updated data files here too, run the ETL from scratch.

**Comment by migbro** [comment]
Data has been loaded into [cBio QA](https://kf-strides-cbioportal-qa.kidsfirstdrc.org/study/summary?id=openpbta). If it looks good, Saksham and I could regroup a bit to fill in the "blanks" of what files had to be merged and how for future load efforts.

**Comment by migbro** [comment]
Ok, CNV has been augmented with WGS neutral calls as requested. Push to prod in progress

**Comment by migbro** [comment]
Prod load looks successful, closing!
