### ISSUE TITLE
Proposed Analysis: Neuroblastoma (NBL) molecular subtyping

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#417]
#### What are the scientific goals of the analysis?
To molecularly subtype neuroblastoma, ganglioneuroblastoma, and ganglioneuroma samples into MYCN amplified or MYCN non-amplified.

#### What methods do you plan to use to accomplish the scientific goals?
This information is usually collected clinically via FISH, for example. For this module, we will want to:
1. For each NBL sample, gather MYCN amplification status from `consensus_wgs_plus_cnvkit_wxs.tsv.gz`
2. Create alterations/output table for matched DNA/RNA biospecimens. Match ID can be adapted from the [independent-samples](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/dev/analyses/independent-samples/util/independent-rna-samples.R) module
3. Add MYCN TPM and MYCN copy number and status to table. It may also be useful to see a quick ascending barplot of MYCN TPM (y-axis) and sample (x-axis) colored by clinical status (see 4 below). See example plot [here](https://www.nature.com/articles/sdata201733/figures/2).
4. Compare the clinical status (currently in `pathology_free_text_diagnosis` to the CNV call). If a match, assign `molecular_subtype` as `NBL, MYCN amplified`. If not a match:
    1. If MYCN is called as amplified but clinical file says non-amplified, assign `NBL, MYCN amplified`.
    2. If MYCN is called non-amplified but clinical file says amplified, plot the CNV data to visualize whether we see focal amplification but the CNV was not called. This can be done by adapting the function here: 
https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/785c3224de29f701b1c1b62841d0f84d46f7eaca/analyses/molecular-subtyping-embryonal/03-clean-c19mc-data.Rmd#L56-L112
    3. If MYCN is called non-amplified but clinical file says amplified and no CNV is found, assess TPM. Is there a cutoff we should be using for amplification based on the plot made in 3 above?  
5. Create output table of DNA and RNA bs_ids + `molecular_subtype`
6. Add analysis to continuous integration

Using one or a few notebooks may be useful here to see inline plots and not need to export them.

#### What input data are required for this analysis?
`histologies.tsv`
`consensus_wgs_plus_cnvkit_wxs.tsv.gz`
`cnv-cnvkit.seg.gz`
`cnv-controlfreec.tsv.gz`
`gene-expression-rsem-tpm-collapsed.rds`

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
1-2 weeks

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@adilahiri 

#### What relevant scientific literature relates to this analysis?
https://www.nature.com/articles/sdata201733
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3784814/

**Comment by adilahiri** [comment]
@jharenza: Thanks for the clarification on the RNA/DNA Ids and TPM.  So I gathered the MYCN - NBL samples in the dataframe`MYCN_df` below.  I first filtered the histology file for Neuroblastoma, Ganglioneuroblastoma, Ganglioneuroma in `hist_filtered_df` and then filtered the `consensus_wgs_plus_cnvkit_wxs.tsv.gz` for MYCN samples in `consensus_filtered_df`.  I then joined these two dataframes using inner join to store the common samples between them in `MYCN_df`.  The  code chunk for this process is as follows:


```
library(dplyr)
library(data.table)
consensus_df<-as.data.frame(fread("/home/rstudio/OpenPedCan-analysis/data/consensus_wgs_plus_cnvkit_wxs.tsv.gz"))
hist_df<- as.data.frame(fread("/home/rstudio/OpenPedCan-analysis/data/histologies.tsv"))
#Step 1: Filter the neuroblastoma, ganglioneuroblastoma, and ganglioneuroma samples from hist file first

hist_filtered_df <- hist_df %>% filter(cancer_group=="Neuroblastoma"|
                                       cancer_group=="Ganglioneuroblastoma"|
                                        cancer_group=="Ganglioneuroma")

# Step 2: Filter the MCYN records from consensus_wgs_plus_cnvkit_wxs.tsv.gz
consensus_filtered_df <- consensus_df %>% filter(gene_symbol=="MYCN")

# Step 3 Join the two data frames to get MYCN details with respect to the diagnosis. Joining with the intersection of the data frames.
MYCN_df <- inner_join(hist_filtered_df,consensus_filtered_df,by= c("Kids_First_Biospecimen_ID" = "biospecimen_id"))
```

It seems that MYCN_df has no RNA samples
```
> print(unique(MYCN_df$experimental_strategy)) # No RNA-Seq
[1] "WGS" "WXS"
> 
> print(unique(MYCN_df$RNA_library)) # No RNA-Seq
[1] NA
```
I believe the file `consensus_wgs_plus_cnvkit_wxs.tsv.gz` has only MYCN for WGS and WXS , but no RNA-Seq samples so do we need to use another file ? 
Also tagging @ewafula , was consulting him on this as well and he volunteered to review this once completed.

**Comment by ewafula** [comment]
@adilahiri, it should not have RNA-seq. Why are you expecting consensus_wgs_plus_cnvkit_wxs.tsv.gz to have RNA-Seq samples? I can work with you tomorrow to come up with logic.

**Comment by adilahiri** [comment]
@ewafula : I figured that as I was working with it a bit earlier. I believed that `consensus_wgs_plus_cnvkit_wxs`  was the only file that contains Gene_Symbol  in it , that's how I can find MYCN samples and relate them to NBLs in the histology file. Now that I think of it, the `tpm file gene-expression-rsem-tpm-collapsed.rds`will have the MYCN samples for which RNA-seq was done.  Will try that and sure will discuss the logic with you tomorrow thanks !!

**Comment by adilahiri** [comment]
In the file`consensus_wgs_plus_cnvkit_wxs.tsv.gz` there are MYCN records with the same` biospecimen_ID `which have differing `status` and `copy numbers.` This is causing the alteration table to be have samples with the same biospecimen_dna_ID and biospecimen_rna_ID.

```
> consensus_df[c(28164530,28164621,25041845,25093610),]
# A tibble: 4 x 7
  biospecimen_id           status        copy_number ploidy ensembl         gene_symbol cytoband
  <chr>                    <chr>               <dbl>  <dbl> <chr>           <chr>       <chr>   
1 TARGET-30-PASXRG-01A-01D amplification          14      3 ENSG00000134323 MYCN        2p24.3  
2 TARGET-30-PASXRG-01A-01D gain                    4      3 ENSG00000134323 MYCN        2p24.3  
3 TARGET-30-PAPVFD-01A-01D loss                    2      3 ENSG00000134323 MYCN        2p24.3  
4 TARGET-30-PAPVFD-01A-01D neutral                 3      3 ENSG00000134323 MYCN        2p24.3  
```

**Comment by ewafula** [comment]
@adilahiri, here are NBL MCYN `clinical patient-status mapping files` for `GMKF` and `TARGET` samples. Some were missing in the v11 in the `pathology_free_text_diagnosis column`.  Will be updated in the v12 final histologies files. 

[target_patient_clinical_mycn_status.tsv.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/9833081/target_patient_clinical_mycn_status.tsv.zip)
[gmkf_patient_clinical_mycn_status.tsv.zip](https://github.com/PediatricOpenTargets/ticket-tracker/files/9833083/gmkf_patient_clinical_mycn_status.tsv.zip)

**Comment by adilahiri** [comment]
Thanks @ewafula will use these files !!

**Comment by adilahiri** [comment]
@jharenza and @ewafula thank you for you help and comments on this module. 
Based on the decision criteria outlined in step 4, and your comments I have classified the Biospecimens accordingly in the [alteration_table](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/molecular-subtyping-NBL/analyses/molecular-subtyping-NBL/results/Alteration_Table.tsv) .  The classes/subtype are indicated in the `subtype` column of the table. Following are the criteria and rules I have used to classify the biosepecimen:

**Case 1:**
  For a given sample, if the `status` and `pathology_free_diagnosis_text` are `amplified` and `MYCN amp` respectively, then the sample is classified as `NBL, MYCN amplified` 
 
 **Case 2:** 
 For a sample, if the `status` is `amplified`  and `pathology_free_diagnosis_text` is `MYCN non-amp`, then the sample is classified as `NBL, MYCN amplified`. 
 
 **Case 3:**
 For a sample, if the `status` has one of these states `loss, gain, or neutral ` and `pathology_free_diagnosis_text` is `MYCN amp`, then classify the sample as `Clincal-Amp Call-Non-Amp` for the time being. 
 
  **Case 4:**
Any remaining samples are kept as NA for the time being. 

Based on the plot in the following [figure](https://raw.githubusercontent.com/PediatricOpenTargets/OpenPedCan-analysis/molecular-subtyping-NBL/analyses/molecular-subtyping-NBL/plots/TPM_Biospecimen_Amp_NonAmp.png) we created in step 3 of the ticket, I have come up with a cutt-off/threshold for classifying samples as `NBL, MYCN amplified` or `NBL, MYCN non-amplified`. This cutoff is at TPM value of 156.12, based on the edge case sample: `TARGET-30-PAPKXS-01A-01D`.

Using this cutt off then:
Any sample with TPM >= 156.12 will be classified as   `NBL, MYCN amplified`  and any sample below this cutoff will be classified as `NBL, MYCN non-amplified`.  

Some of significant changes, or samples where the currently assigned subtype will change due to this cut off are listed in the [Suggested_Change](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/blob/molecular-subtyping-NBL/analyses/molecular-subtyping-NBL/results/Suggested_Change.tsv) table.  The current subtype are in the column `subtype_current` and the column `subtype_suggested` contains the reassigned subtype when the above mentioned cutoff is used.

Please let me know your thoughts and feedback on this.

**Comment by ewafula** [comment]
@adilahiri, one more ask before reviewing the PR. Please include a check to make sure samples between `wgs/wxs` have the same status mycn status calls.  All samples in `target` are `wgs` and all samples in `gmkf `are `wxs`. You'll need to make comparisons for patient IDs (`Kids_First_Participant_IDs`)  that overlap between the two cohorts. 
```
> read_tsv("../../data/histologies.tsv") %>% filter(cancer_group == "Neuroblastoma", experimental_strategy == "WGS" | experimental_strategy == "WXS") %>% select(cohort, experimental_strategy) %>% distinct()
# A tibble: 3 x 2
 cohort experimental_strategy
 <chr> <chr>         
1 GMKF  WGS          
2 PBTA  WGS          
3 TARGET WXS
```

You also have two PR submitted for this ticket. Could remove the PR that is not needed?

**Comment by ewafula** [comment]
> @adilahiri, one more ask before reviewing the PR. Please include a check to make sure samples between `wgs/wxs` have the same status mycn status calls. All samples in `target` are `wgs` and all samples in `gmkf `are `wxs`. You'll need to make comparisons for patient IDs (`Kids_First_Participant_IDs`) that overlap between the two cohorts.
> 
> ```
> > read_tsv("../../data/histologies.tsv") %>% filter(cancer_group == "Neuroblastoma", experimental_strategy == "WGS" | experimental_strategy == "WXS") %>% select(cohort, experimental_strategy) %>% distinct()
> # A tibble: 3 x 2
>  cohort experimental_strategy
>  <chr> <chr>         
> 1 GMKF  WGS          
> 2 PBTA  WGS          
> 3 TARGET WXS
> ```
> 
> You also have two PR submitted for this ticket. Could remove the PR that is not needed?


@adilahiri, you also need to make sure the `sample_ids` are similar for the  `Kids_First_Participant_IDs` with overlapping `Kids_First_Participant_IDs` between the two cohorts.

**Comment by adilahiri** [comment]
Ok @ewafula , will do the check and put the qc table in the results.
