### ISSUE TITLE
Updated CI testing dataset to enrich with tumor-only and tumor-normal samples for batch correction 

### ISSUE THREAD

**Issue by ewafula** [PediatricOpenTargets/ticket-tracker#460]
#### What analysis module should be updated and why?
[create-subset-files](https://github.com/PediatricOpenTargets/OpenPedCan-analysis/tree/dev/analyses/create-subset-files) module

#### What changes need to be made? Please provide enough detail for another participant to make the update.
1). Create a script to determine a list of bs_ids required for tumor-only (`molecular_subtype`) and tumor-normal (`cancer_group` and `gtex_subgroup`) RNA-Seq batch correction analyses
2)  Include a few bs_ids with contrasting molecular subtypes in the CI subset counts matrix for testing the tumor-only batch correction process
3) Include a few corresponding `cancer_group` and `gtex_subgroup` bs_ids in the CI subset counts matrix for testing the tumor-normal batch correction process

#### What input data should be used? Which data were used in the version being updated?
 - v11 histologies.tsv
 - v11  gene-counts-rsem-expected_count-collapsed.rds

#### When do you expect the revised analysis will be completed?
Next sprint 

#### Who will complete the updated analysis?
@ewafula

**Comment by aadamk** [comment]
Adding a couple of thoughts here for this to pass CI.
1. For tumor-only: A random sample of 10 bs-ids per `molecular_subtype` in cancer groups `'Diffuse midline glioma, High-grade glioma/astrocytoma'` balanced for `RNA_library` (e.g. roughly even representation of poly-A and ribo-deplete samples per subtype where possible). 
2. For tumor-normal: A random sample of 20 GTEx from subgroups `'Brain - Cortex,Brain - Cerebellum'`. 

I'm thinking this should be sufficient to pass CI since the script selects based on cancer group, corrects for batch by RNA_library, runs molecular_subtype-based DGE analysis (tumor-only), tumor versus normal in the GTEx script (script 02).
