### ISSUE TITLE
Create list of EFO/MONDO ids which need term changes

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#465]
#### What data file(s) does this issue pertain to?
`efo-mondo-map-prefill-auto.tsv`

#### What release are you using?

v12

#### Put your question or report your issue here.
Create a list of IDs which should have descriptions changed to be consistent with current terms. Eg Ependymoblastoma --> ETMR

**Comment by chinwallaa** [comment]
@sangeetashukla I believe you are working on this, can you confirm. Need to confirm that it matches the disease mapping file in MTP annotation module (per @ewafula )

**Comment by sangeetashukla** [comment]
> @sangeetashukla I believe you are working on this, can you confirm. Need to confirm that it matches the disease mapping file in MTP annotation module (per @ewafula )

@chinwallaa I started reviewing the mtp-diseases-mapping.tsv.gz and mtp-targets-mapping.tsv.gz results mapping files from MTP annotation module, to ensure the gene_match and efo-mondo-mapping modules are up-to-date. But this is still a work in progress since I switched gears last week to do some PR reviews. But yes, this is in the pipeline.

**Comment by jharenza** [comment]
Closing as MTP is ending. Can revisit in the future if needed.
