### ISSUE TITLE
`All Cohorts` dataset values appearing when 0 or 1 other datasets are present

### ISSUE THREAD

**Issue by zdorman** [PediatricOpenTargets/ticket-tracker#473]
#### What data file(s) does this issue pertain to?

**MTP Somatic Alteration tables filtered-for-gencode-v39-and-OT**
    - SNV by Gene: `gene-level-snv-consensus-annotated-mut-freq.jsonl`
    - SNV by Variant: `variant-level-snv-consensus-annotated-mut-freq.jsonl`
    - CNV by Gene: `gene-level-cnv-consensus-annotated-mut-freq.jsonl`
    - Fusion by Gene: `putative-oncogene-fused-gene-freq.jsonl`
    - Fusion: `putative-oncogene-fusion-freq.jsonl`

#### What release are you using?

v11 

#### Put your question or report your issue here.

**Summary**
The `All Cohorts` dataset value is appearing at inappropriate times in MTP tables. The current issue is similar to https://github.com/PediatricOpenTargets/ticket-tracker/issues/235.

Calculations of `All Cohorts` are duplicated or appearing when not needed in evidence containing 3 diseases:
`EFO_0000500` (ganglioneuroma)
`EFO_0000502` (ganglioneuroblastoma)
`EFO_0000621` (neuroblastoma)

**Details**
The issue is present in two ways:
1. Target-Disease combinations with ONLY `All Cohorts` dataset
    Problem appears only twice: 2 targets in `EFO_0000500` (ganglioneuroma) within the SNV files
    - [PLEKHH3 in ganglioneuroma](https://moleculartargets.ccdi.cancer.gov/evidence/ENSG00000068137/EFO_0000500)
    - [CCDC28A in ganglioneuroma](https://moleculartargets.ccdi.cancer.gov/evidence/ENSG00000024862/EFO_0000500)
![image](https://user-images.githubusercontent.com/82673924/209836290-6bfa1f9d-b017-4df9-8013-a570a619f299.png)

2. Target-Disease combinations with ONLY 2 dataset values, where one is `All Cohorts`
    Problem appears in 10k+ combinations across all files, but seems limited to targets across 3 diseases. Examples:
    - [FGR in ganglioneuroma](https://moleculartargets.ccdi.cancer.gov/evidence/ENSG00000000938/EFO_0000500) (SNV)
    - [KRIT1 in neuroblastoma](https://moleculartargets.ccdi.cancer.gov/evidence/ENSG00000001631/EFO_0000621) (SNV, Fusion)
    - [TUSC2P1 in ganglioneuroblastoma](https://moleculartargets.ccdi.cancer.gov/evidence/ENSG00000285470/EFO_0000502) (CNV)
![image](https://user-images.githubusercontent.com/82673924/209836211-a39134dc-b2f6-4d07-992e-52feefe2200e.png)

**Preferred Display**
For any given evidence table (SNV, CNV, Fusion), the All Cohorts rows should only appear for target-disease combinations for which more than one unique dataset is present. 
Examples:
1. SNV evidence from only one dataset: Display that dataset but no `All Cohorts`
2. Fusion evidence from two different datasets: Display both datasets AND `All Cohorts` 
3. SNV evidence from only one dataset and Fusion evidence from only one different dataset: Display each dataset in the separate MTP tables but no `All Cohorts`

**Comment by chinwallaa** [comment]
Thanks @zdorman .  We can review this on our upcoming 01/13  MTP planning meeting.   Some cohorts contributing towards All Cohorts don't meet the >3  # of samples or have no mutation call for a particular gene, That's why the denominator values are larger than individual cohort for such cases. In some cases the individual cohorts do not  satisfy the requirements but do for All cohorts

**Comment by zdorman** [comment]
Hi @chinwallaa @ewafula I see that this one was closed after we discussed it on the 1/27/23 call, but I don't think we fully explained the "Issue Type 2" above. 

For Issue Type 1, where some target-disease combos appear with ONLY an All Cohorts dataset, I can understand a situation where multiple datasets are below inclusion threshold, but the combination is above. I'm fine with this as-is as an edge case. 

For Issue Type 2, where many (10k+) target-disease combos appear with ONLY 1 dataset + an All Cohorts dataset, the 'Total alterations / Subjects in dataset' still seems problematic. 

For instance, in the TUSC2P1 in ganglioneuroblastoma example above: 
Total alterations / Subjects in dataset = 24/54 for All Cohorts
Total alterations / Subjects in dataset = 24/34 for TARGET
Does this mean that there are 0 samples in a non-TARGET dataset of 20 that were included in the All Cohorts? If this is a correct way to interpret this, is this valuable to include? 
If this means that there are at least 1 samples in a non-TARGET dataset of 20 that were included in the All Cohorts, then why does the numerator not increase along with the denominator?

**Comment by jharenza** [comment]
Hi @zdorman. To respond:
>Does this mean that there are 0 samples in a non-TARGET dataset of 20 that were included in the All Cohorts? If this is a correct way to interpret this, is this valuable to include?

Yes, this is correct, and what this is telling us at the moment is that only WXS samples (TARGET) are showing this deep deletion, but the WGS (GMKF) are not, and this might be worth revisiting through our analysis pipelines to see if something odd is happening that dels are being called only in one experimental strategy - is this an artifact? 
- We currently only do consensus CNV calls (2/3) on WGS and not WXS - this was because one of the callers  (MantaSV) was only avail to run on WGS), in v11. We defaulted to use CNVkit only calls for WXS. It is possible that this is called only in CNVkit and not the others and hence no consensus. However, in v12, we are swapping out MantaSV for GATK CNV since Manta is geared more to SVs. This issue may or may not remain - yet to be seen.
- After v12, we may explore doing a consensus on WXS - we just did not have 3 callers in the past to do so, and now we do, so we can explore this. Will take some time. Don't think we need to do anything here in the meantime, but we can come back to these in v12, see if this persists and for how many genes, and do some deeper diving.

>If this means that there are at least 1 samples in a non-TARGET dataset of 20 that were included in the All Cohorts, then why does the numerator not increase along with the denominator?

Taking TUSC2P1 example, this means 24/54 in all cohorts were the TARGET 24/34 and the remaining 30 (54-24) would be non-TARGET and have no deletion. Does this make sense?
