### ISSUE TITLE
Add pedcbio map RNA/DNA IDs plus case set ids

### ISSUE THREAD

**Issue by jharenza** [PediatricOpenTargets/ticket-tracker#93]
#### What are the scientific goals of the analysis?
Per discussion in #83, we will need to generate case set ids for pedcbio for every combination of `cohort+cancer_group` and `cancer_group` for linking within the SNV files. 

#### What methods do you plan to use to accomplish the scientific goals?
To do this, first, we need to add code to create a list of the sample IDs used in pedcbio. Then, we will have to add to each sample metadata for the groups in which it belongs.

#### What input data are required for this analysis?
`histologies.tsv`

#### How long do you expect is needed to complete the analysis? Will it be a multi-step analysis?
2 days

#### Who will complete the analysis (please add a GitHub handle here if relevant)?
@migbro 

#### What relevant scientific literature relates to this analysis?
NA

cc @allisonheath @logstar @kalletlak

**Comment by migbro** [comment]
For now, I can add a script that generates the cBio IDs to fit PBTA and also case lists. I'll probably start by adding it to the cBio etl repo first, since all other work is there, then port over/link if needed. The mixed cohorts will be tricky in the future as rules used to build cBio-compatible IDs may change between them.

**Comment by migbro** [comment]
So given that this is more related to cBio, and `cancer_group` gets added to the cBio formatted sample datasheet, I wonder if it would be better for me use that as input instead of the histologies sheet. Those case lists are also a cBio formatted file that gets used to populate that drop down and also has some functionality from a query point of view.

**Comment by jharenza** [comment]
> So given that this is more related to cBio, and `cancer_group` gets added to the cBio formatted sample datasheet, I wonder if it would be better for me use that as input instead of the histologies sheet. Those case lists are also a cBio formatted file that gets used to populate that drop down and also has some functionality from a query point of view.

It really doesn't matter, as long as we have a mapping of:
`cohort+cancer_group` and `case_set_id`
and
`cancer_group` and `case_set_id`

**Comment by migbro** [comment]
Ok, I've loaded the cases lists onto to QA. So if you select the study, and hit query by gene, you'll see the new lists in the dropdown - just need to scroll up and down. If I choose `Medulloblastoma,` and gene `CTNNB1`, th eurl that pops up in the browser is: https://kf-strides-cbioportal-qa.kidsfirstdrc.org/results/oncoprint?genetic_profile_ids_PROFILE_MUTATION_EXTENDED=ped_opentargets_2021_mutations&genetic_profile_ids_PROFILE_COPY_NUMBER_ALTERATION=ped_opentargets_2021_cna&genetic_profile_ids_PROFILE_MRNA_EXPRESSION=ped_opentargets_2021_rna_seq_v2_mrna_median_Zscores&cancer_study_list=ped_opentargets_2021&Z_SCORE_THRESHOLD=2.0&RPPA_SCORE_THRESHOLD=2.0&data_priority=0&profileFilter=0&case_set_id=ped_opentargets_2021_medulloblastoma&gene_list=CTNNB1&geneset_list=%20&tab_index=tab_visualize&Action=Submit

It's not pretty, but it works. If that looks ok, I can push to prod

**Comment by logstar** [comment]
@migbro Thank you for adding the case lists!

The following URLS also work:

- https://kf-strides-cbioportal-qa.kidsfirstdrc.org/results/oncoprint?cancer_study_list=ped_opentargets_2021&case_set_id=ped_opentargets_2021_medulloblastoma&Action=Submit&gene_list=CTNNB1
- https://kf-strides-cbioportal-qa.kidsfirstdrc.org/results/mutations?cancer_study_list=ped_opentargets_2021&case_set_id=ped_opentargets_2021_medulloblastoma&Action=Submit&gene_list=CTNNB1

**Comment by jharenza** [comment]
Great, thank you! Note @logstar - this is at the `cancer_group` level. 

@migbro can you also add cohort level to this (the results will all the be same at the moment, but we can add the links into the SNV table properly)

**Comment by logstar** [comment]
@migbro I wonder if you could share your code for converting cohort and histology/cancer_group (whichever you used in the QA) to `case_set_id`s. I am planning to use it for creating a (`cohort`, `cancer_group`)->`case_set_id` mapping list.

@jharenza Does the following procedure look good?

- Add `cancer_group` level URLs to SNV table rows that have more than one cohorts.
- Add (`cohort`, `cancer_group`) level URLs to SNV table rows that have only one cohort. 
- Add blank `''` strings to SNV table rows that have `cancer_group` or `cohort` not present in the cbio case set IDs.

**Comment by migbro** [comment]
Hi @logstar , sure. I actually did this part using the cBio datasheet because the cBio-compatible IDs are already there. Generating those cBio IDs was done as part of the data sheet creation process, currently found here: https://github.com/kids-first/kf-cbioportal-etl/blob/mb-add-opentargets/COLLABORATIONS/openTARGETS/clinical_to_datasheets.py. It's a kids first private repo though, so if you can't access that, I could consider making it public while making it clear that the code is NOT ready for solid reliable production use. We are working on improving infrastructure to make that more possible, but the code gets the job done for now.

**Comment by logstar** [comment]
@migbro Thank you. I do not have access to the repository, but I think I only need the part of code for creating `case_set_id` strings, e.g. how `'Medulloblastoma'` (or some other values in the cBio internal datasheet) is converted to `'ped_opentargets_2021_medulloblastoma'`.

I guess the code is like `case_set_id = 'ped_opentargets_2021_' + cbio_internal_datasheet_value.lower()`, but the conversion code should be more complex, in order to handle histology that has non alpha-num characters like `'Low-grade glioma/astrocytoma'`.

If the values in cBio internal datasheet are very different from the histology values, could you also share all unique values that represent histology in cBio internal datasheet?

**Comment by migbro** [comment]
@logstar , I see. So, to start, I call it `HISTOLOGY` in the datasheet, but it's a direct analog of the `cancer_group` field in the `histologies.tsv` sheet. The code was pretty simple. Jo Lynne instructed me not to bother creating a case list for any histology or histology-cohort combo with less than 5 samples. So far this works:
```
hist_stable = hist.lower().replace(" ", "_").replace("/", "_")
cohort_stable = cohort.lower().replace(" ", "_").replace("/", "_")
cancer_group_case_set_id='ped_opentargets_2021_' + hist_stable
cohort_group_case_set_id='ped_opentargets_2021_' + cohort_stable + "_" + hist_stable
```
So far `-` is tolerated, so that stays, and in the future we may have to adapt if other non-alphanumeric chars pop up.

**Comment by migbro** [comment]
Or at least I should say, I assume the latter cohort_group will work. Loading that now onto the portal. It takes about 45 minutes...

**Comment by logstar** [comment]
@migbro Thank you for the code.

I also wonder if I could get all unique `case_set_id`s through any cBio API. I am going to check whether a converted `cohort_group_case_set_id` is present in the cBio dataset. For example, cBio dataset only has PBTA cohort, so the converted `cohort_group_case_set_id` 'ped_opentargets_2021_neuroblastoma_gmkf' from my side will not be used to generate cBio URLs.

**Comment by migbro** [comment]
Ok, the cohort + cancer_group case sets have been added as well in QA. I think I will just push that to prod since it's pretty unlikely anything is wrong. I can abort within in the next hour if anyone disagrees :)

**Comment by logstar** [comment]
I will use the following URL to pull all `case_set_id`s from cBio.

<https://pedcbioportal.kidsfirstdrc.org/api/studies/ped_opentargets_2021/sample-lists>

Found pedcbio public API here, <https://pedcbioportal.kidsfirstdrc.org/api/swagger-ui.html>.

**Comment by migbro** [comment]
Oh, that's pretty cool! Although, it seems to pull up only the standard cBio lists and not the custom ones. If that is enough, then great!

**Comment by logstar** [comment]
> Oh, that's pretty cool! Although, it seems to pull up only the standard cBio lists and not the custom ones. If that is enough, then great!

The QA website seems to have all case_set_ids, <https://kf-strides-cbioportal-qa.kidsfirstdrc.org/api/studies/ped_opentargets_2021/sample-lists>. Not sure if the main site would work the same.

Seems the main site is just down, <https://pedcbioportal.kidsfirstdrc.org/study/summary?id=ped_opentargets_2021> .

**Comment by migbro** [comment]
Ah, I see now. I am working on putting it on the main site now - perhaps the loader encountered an error 😩 . I'll try restarting it. Have a good weekend!

**Comment by logstar** [comment]
Thanks. You too. Have a good weekend!

**Comment by migbro** [comment]
Hmm, so is this done now? I can't remember if there is anything left to do.

**Comment by jharenza** [comment]
yup, done
